version: '3'

services:
  php:
    container_name: 'demo-api-php_fpm'
    network_mode: bridge
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/php:/usr/local/etc/php:ro,cached
      - .:/app:rw,cached
      - ./.composer:/var/www/.composer
    expose:
      - 9000
    user: '1000'
    links:
      - db

  nginx:
    container_name: 'demo-api.docker'
    network_mode: bridge
    build: .docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/app/public:ro
      - ./.docker/nginx/etc/nginx:/etc/nginx:ro,cached
    links:
      - php

  db:
    container_name: 'demo-api-db'
    network_mode: bridge
    image: mysql:5.7
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
